# -*- coding: utf-8 -*-
"""CF3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzcQbQ2c5BXRjzW0v10QFDf6kYMB6-SD
"""

s=input()
countR=s.count('R')
countU=s.count('U')
countD=s.count('D')
countL=s.count('L')

X=abs(countR-countL)
Y=abs(countU-countD)

if len(s)%2!=0:
  print(-1)
else:
  print((X+Y)//2)

